name: Fetch and Commit

on:    
  workflow_dispatch:
    inputs:
      cs_tools_version:
        description: "The CS Tools version to target for a manual run."
        required: false
        type: string

      env_name:
        description: "The name of the environment you're exporting TML from."
        required: false
        type: string

      source_org:
        description: "The Org to switch to before extracting TML."
        required: true
        type: string
        default: Primary

      metadata_types:
        description: "The type(s) of TML to export, commad separated."
        required: true
        type: string
        default: ALL

      tags:
        description: "TML tagged with these name(s), commad separated."
        required: false
        type: string

      directory:
        description: "Directory to save TML files to."
        required: true
        type: string
        default: .

env:
    CS_TOOLS_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.cs_tools_version || 'v1.6.1' }}
    CS_TOOLS_THOUGHTSPOT__URL: ${{ secrets.DEV_THOUGHTSPOT_URL }}
    CS_TOOLS_THOUGHTSPOT__USERNAME: ${{ secrets.DEV_THOUGHTSPOT_USERNAME }}
    CS_TOOLS_THOUGHTSPOT__SECRET_KEY: ${{ secrets.DEV_THOUGHTSPOT_SECRET_KEY }}
    
    DIRECTORY: ${{ github.event_name == 'workflow_dispatch' && inputs.directory || 'dogfood' }}
    TS_ENV_NAME: ${{ github.event_name == 'workflow_dispatch' && inputs.env_name || 'ts-dev' }}
    TS_SOURCE_ORG_ID: ${{ github.event_name == 'workflow_dispatch' && inputs.source_org || 'ArjunB' }}
    TS_METADATA_TYPES: ${{ github.event_name == 'workflow_dispatch' && inputs.metadata_types || 'ALL' }}
    TS_OBJECT_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.tags || 'migrate' }}
    TS_COMMIT_MESSAGE: "AUTOMATED >> TS-CI '${{ github.event.workflow }}' @ ${{ github.event.repository.updated_at }}"

jobs:
  run_commit_api: 
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout ${{ env.TS_ENV_NAME }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TS_ENV_NAME }}
          token: ${{ secrets.G_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install CS Tools
        run: pip install "cs_tools[cli] @ https://github.com/thoughtspot/cs_tools/archive/${{ env.CS_TOOLS_VERSION }}.zip"

      - name: Export TML Files
        run: |
          cs_tools tools scriptability checkpoint \
            --directory "${{ env.DIRECTORY }}/" \
            --environment "${{ env.TS_ENV_NAME }}" \
            --metadata-types ${{ env.TS_METADATA_TYPES }} \
            --tags "${{ env.TS_OBJECT_TAG }}" \
            --org "${{ env.TS_SOURCE_ORG_ID }}" \
            --config ENV:

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Commit Changes
        run: |
          git add ${{ env.DIRECTORY }}/
          git commit -m "${{ env.TS_COMMIT_MESSAGE }}"

      - name: Push Changes
        run: |
          git push origin ${{ env.TS_ENV_NAME }}
